[tool.poetry]
name = "prob-gbt"
version = "0.1.0"
description = ""
authors = ["Ilya Fastovets <ilya.fastovets@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
